services:
  - type: web
    name: whale-requirements-engineering
    env: python
    buildCommand: pip install -r requirements.txt
<<<<<<< HEAD
    startCommand: PYTHONPATH=AutoTestGen_MAPS gunicorn app:app --chdir AutoTestGen_MAPS -w 4 -b 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        generateValue: true
=======
    startCommand: PYTHONPATH=. gunicorn app:app --chdir . -w 4 -b 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        generateValue: true 
>>>>>>> 85f8878 (First Commit)
